import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {designCourses,coursePoint,courseTangent} from '../src/course.js';
const pair=n=>{
  if(n<0||n>=91*91||!Number.isInteger(n))throw Error('Course coordinate is outside its encoding range');
  return String.fromCharCode(35+Math.floor(n/91),35+n%91);
};
export const encodeCourse=rows=>rows.map(([x,z,yaw,width])=>{
  if(!Number.isInteger(width)||width<0||width>=91)throw Error('Invalid checkpoint width');
  return pair(Math.round(x*4)+2048)+pair(Math.round(z*4)+2048)+pair(Math.round((yaw+4)*1000))+String.fromCharCode(35+width);
}).join('');
export function generateCourseCodes(){
  return Object.fromEntries(Object.values(designCourses()).map(course=>[course.id,{
    name:course.name,lighting:course.lighting,aiSkill:course.aiSkill,
    gates:encodeCourse(course.gates.map(g=>[g.x,g.z,Math.atan2(g.tangent.x,g.tangent.z),g.width])),
    grid:encodeCourse([0,1,2,3].map(id=>{
      const t=-.019-Math.floor(id/2)*.013,p=coursePoint(t,course),n=courseTangent(t,course),lane=id%2?5:-5;
      return [p.x+n.z*lane,p.z-n.x*lane,Math.atan2(n.x,n.z),0];
    }))
  }]));
}
export async function writeCourseCodes(){
  await writeFile(new URL('../src/course-codes.js',import.meta.url),'// Generated by npm run courses: quarter-unit positions, milliradian headings.\nexport const COURSE_CODES='+JSON.stringify(generateCourseCodes())+';\n');
}
if(process.argv[1]===fileURLToPath(import.meta.url))await writeCourseCodes();
