import {writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {COURSES} from '../src/course.js';
import {racingLine} from '../src/simulation.js';
export function generateRacingLines(){
  return Object.fromEntries(Object.values(COURSES).map(course=>[course.id,[0,1,2,3].map(id=>racingLine(course,id).map((p,i)=>{
    const g=course.gates[i];
    for(let j=-4;j<=4;j++){
      const offset=j*(g.width-8)/4;
      if(p.x===g.x+g.tangent.z*offset&&p.z===g.z-g.tangent.x*offset)return String.fromCharCode(52+j);
    }
    throw Error('Racing line is outside its encodable buoy corridor');
  }).join(''))]));
}
export async function writeRacingLines(){
  await writeFile(new URL('../src/racing-lines.js',import.meta.url),'// Generated by npm run courses. Digits encode -4..4 corridor offsets for each rider.\nexport const LINE_CODES='+JSON.stringify(generateRacingLines())+';\n');
}
if(process.argv[1]===fileURLToPath(import.meta.url))await writeRacingLines();
